[tool.poetry]
name = "wanga"
version = "0.1.0"
description = "A library for interacting with Large Language Models."
authors = ["Artur Chakhvadze <norpadon@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">3.10,<4.0"
jinja2 = "^3.1.4"
attrs = "^23.2.0"
docstring-parser = "^0.16"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
pytest-dotenv = "^0.5.2"
openai = "^1.35.3"
anthropic = "^0.29.0"
ruff-lsp = "^0.0.53"
isort = "^5.13.2"
pyright = "^1.1.369"
pydantic = "^2.7.4"

[tool.poetry.group.docs.dependencies]
sphinx = "^7.3.7"
sphinx-rtd-theme = "^2.0.0"
sphinxcontrib-napoleon = "^0.7"
toml = "^0.10.2"

[tool.pyright]
pythonVersion = "3.10"
typeCheckingMode = "standard"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
