name: lint
on:
  push:
    tags: '*'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: abatilo/actions-poetry@v3
      - name: Install dependencies
        run: poetry install --with dev && echo "$(poetry env info --path)/bin" >> $GITHUB_PATH
      - uses: chartboost/ruff-action@v1
      - uses: jakebailey/pyright-action@v2
