name: tests
on:
  push:
    tags: '*'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - uses: abatilo/actions-poetry@v3
    - name: Install dependencies
      run: poetry install --with dev
    - name: Run tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: poetry run pytest -vv

